### ISSUE TITLE
Crashing when resizing window

### ISSUE THREAD

**Issue by mszulen** [speccytools/fuse-for-macosx#2]
On MacBook Air M1 the 1.5.6 crashes every time I resize the window. Error dump attached.
[fuse x error dump.txt](https://github.com/speccytools/fuse-for-macosx/files/9994714/fuse.x.error.dump.txt)

**Comment by desertkun** [comment]
Yeah, some weird multithreading issue. I'll look into it. Meantime, you can just use `View -> Zoom 2x` etc

**Comment by mszulen** [comment]
Great! Thanks for a quick response! :)

**Comment by desertkun** [comment]
Please check this build https://github.com/speccytools/fuse-for-macosx/releases/tag/fusex-1.5.6-3

Does it fix it?

**Comment by mszulen** [comment]
Apologies for late confirmation here. As per my facebook response a few days ago, yes, it did fix the issue.
Thank yoU!
