### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Alvarez81** [speccytools/fuse-for-macosx#3]
Hi, this port to be used with Apple Silicon CPU is great.
Why 1.5.6 the fuse is available on **revision 1.6.0**, could you update ? ...please

_Fuse lacks a "Point&Click" virtual keyboard already present on other Mac emulators (Vamiga, VirtualC64, ZxPoly etc) could it be implemented ?_

**Comment by desertkun** [comment]
I'll take a look. Last time I checked, fuse for mac, a fork I am forked from, lacks updates, so I'd have to jump upstream and upgrade from regular fuse.

**Comment by desertkun** [comment]
I was able to merge the changes on my my machine. What changes are you expecting from 1.6.0 that's not in 1.5.6? So I'd verify they're there.

**Comment by Alvarez81** [comment]
In 1.6.0 some z80 errors were solved (not NOP instruction yet) [see zip]. Other minor bugs removed.
[z80test-1.2.zip](https://github.com/speccytools/fuse-for-macosx/files/10018695/z80test-1.2.zip)

**Comment by Alvarez81** [comment]
In 1.6.0 some z80 errors were solved (not NOP instruction yet) [see zip]. Other minor bugs removed.
[z80test-1.2.zip](https://github.com/speccytools/fuse-for-macosx/files/10018695/z80test-1.2.zip)

**Comment by Alvarez81** [comment]
In 1.6.0 some z80 errors were solved (not NOP instruction yet) [see zip]. Other minor bugs removed.

**Comment by Haroldo64** [comment]
Hi, version 1.6 is more stable, some fixes on filters ì, various minor bugfixes and better spectrum compatibility from 1.7 bugfixes.

To date, the 1.6 release is the best ever in terms of compatibility.

Too bad that there is still a lack of a virtual keyboard (on screen like Virtualc64 emulator) about zx, zx+ skin layout that can be used with the mouse so as not to confuse the keys.

Thanks for compiling for Apple Silicon M1 there are a lot of us that are using new macs

**Comment by PakkunKinoppi** [comment]
This is really good news that an executable and updated version for Apple Silicon of our beloved Fuse emulator is created.
**I hope FuseX can be a point of reference for all MacOS users,**

Like a lot this name: **FuseX** :1st_place_medal:

**Comment by rossimariolee** [comment]
Perfect, excellent news: we are waiting for the 1.6 revision for Mac M1 Cpu.

Make a page suitable for FuseX here and not a subdirectory of _speccytools_ : **FuseX must grow :+1:**  

Thanks, many thanks!!!

**Comment by puleyo2000** [comment]
Good news I think.
Finally an updated **Fuse** ZXSpectrum emulator for MacOS M1.
I sincerely hope this is a real start, with updates and improvements.
I follow with pleasure, well done!

**Comment by desertkun** [comment]
I've pushed https://github.com/speccytools/fuse-for-macosx/releases/tag/fusex-1.6.0 tell me how it works for you. One hassle was to make opening recent files working again since of new app sanbox requirement.
TTX2000S is disabled for now b/c I need to figure out how does it work and how to test it, it seems like there's some kind of pipes.

**Comment by puleyo2000** [comment]
It works well on my M1, only two things:

1) no drag and drop games tap or tzx onto the fusex screen (only load from menu)

2) no ULA plus option seen 😢  😿  😭 

bye
