### ISSUE TITLE
Drag'n'drop does not work on MBP M1

### ISSUE THREAD

**Issue by Alvarez81** [speccytools/fuse-for-macosx#6]
Hi, I do not know if FuseX has got drag'n'drop on X86 mac but does not work on my MBP M1

I cannot drop neither .tap nor .tzx and .z80 files

**Comment by Alessandro1970** [comment]
Hi, drag'n'drop doesn't work on my MBP arm too.

**Comment by desertkun** [comment]
Ok was able to figure out how the thing is supposed to work. I'll push a release in following days.

**Comment by desertkun** [comment]
@Alvarez81 @Alessandro1970 try this https://github.com/speccytools/fuse-for-macosx/releases/tag/fusex-1.6.0-2
